project: "iotex-explorer"
env: development

server:
  protocol: "http:"
  host: "localhost"
  port: 4004
  staticDir: "./dist"
  routePrefix: "/"

gateways:
  logger:
    enabled: true
    baseDir: "/var/log/"
    topicName: iotex-explorer
    level: "debug"
    kafka:
      leafHost: "localhost"
      leafPort: 9093
  iotexCore:
    serverUrl: http://localhost:14004/

  walletCore:
    serverUrl: localhost:42124


analytics:
  googleTid: UA-XXXXXXXXX-1
